rancher/opni

src/training_controller/Dockerfile
src/training_controller/README.md
src/training_controller/prepare_training_logs.py
src/training_controller/rbac_role.yaml
src/training_controller/rbac_role_binding.yaml
src/training_controller/rbac_service_account.yaml
src/training_controller/requirements.txt
src/training_controller/training_controller.py
src/training_controller/training_controller.yaml

Add the training-controller service to Github repository where the control will launch a Nulog training job upon receiving a signal from the Nats subject "train"

Add training-controller service to repository

---

src/nulog-train/Dockerfile
src/nulog-train/NuLogModel.py
src/nulog-train/NuLogParser.py
src/nulog-train/NuLogTokenizer.py
src/nulog-train/README.md
src/nulog-train/nulog_train.yaml
src/nulog-train/requirements.txt
src/nulog-train/train.py

Add nulog-train job to Github repository which will train a Nulog model on data dumped from Elasticsearch.

Add nulog-train service to repository

---

src/models/nulog/NuLogParser.py
src/models/nulog/NuLogTokenizer.py
src/models/nulog/inference.py

This PR fixes 2 bugs:
1. a corner case that predictions results not calculated correctly
2. handle the case that input message is empty string.

nulog model bug fix.

---

src/preprocessing-service/masker.py
src/preprocessing-service/preprocess.py

Add log timestamp parsing to preprocessing service

klog timestamp parsing

---

src/drain-service/build.sh
src/drain-service/drain3/file_persistence.py
src/drain-service/requirements.txt
src/k8s/services/drain-service.yaml

DRAIN models will now be able to be saved and loaded from Minio

Have DRAIN models saved and loaded from Minio

---

pkg/demo/services.go

Set up shared volume for training data

Update to use local training data

---

.drone.yml
images/python/Dockerfile
images/python/Dockerfile.elasticdump
pkg/demo/infra.go
pkg/demo/services.go

This PR:
- Updates the drone build to use caches from existing images
- Publishes the builder images for caching across steps
- Separates out the build of the elasticdump image so as to be quicker
- Updates the operator to use the new environment variables for services

Update Drone build, and update ENV vars for services

---

config/samples/demo_v1alpha1_opnidemo.yaml

I updated the demo_v1alpha1_opnidemo.yaml file with a more accurate config so that Tilt can operate correctly.

Config in the demo_v1alpha1_opnidemo.yaml file changed to current keys:values

---

images/python/requirements.txt

Update the requirements.txt file to include some additional libraries which are necessary for opni-metric-anomaly-detector service.

Update requirements.txt so it includes the necessary libraries for opni-metric-anomaly-detector service.

---

images/python/requirements.txt

Elasticsearch version is updated to version 7.13.0

Update elasticsearch version to 7.13.0

---

deploy/examples/logAdapters/logAdapter_k3s_openrc.yaml
deploy/examples/logAdapters/logAdapter_k3s_systemd.yaml
deploy/examples/logAdapters/logAdapter_rke.yaml
deploy/examples/logAdapters/logAdapter_rke2.yaml

Add opnicluster ref to LogAdapter examples

---

deploy/kustomization.yaml
deploy/patches/insights.yaml

Updated Kustomize to allow addition of the Insights Service. The new patch file adds the yaml to create it, and updated the kustomization.yaml to include it when comment is removed.

Updated Kustomize to allow addition of the Insights Service

---

pkg/resources/opnicluster/services.go

This fixes the bug found as part of #172

Fix issue with disabled prometheus service

---

packages/opni-agent/opni-agent/charts/templates/deployment.yaml
pkg/resources/opnicluster/elastic/indices/opni_settings.go
pkg/util/opensearch/opensearch.go

* Fixes the insecure agent flags
* Adds new settings to the index template
Fixes #320 
Fixes #319

Update index settings and agent flags

---

apis/v1beta2/logadapter_webhook.go
pkg/events/events.go
pkg/util/generic.go

Fixes #338
Fixes #340 
* If event is nil do nothing when procesing
* Add pod_name field if the involved object is a pod

Check for nil in events shipper

---

pkg/resources/gateway/certs.go
pkg/resources/gateway/gateway.go

Create certifcate to use for gateway ingress

---

aiops/apis/setup.py
aiops/requirements.txt

This PR updates the setup.py file and requirements.txt to point to the updated version name for the opni-proto Pypi package.

Update setup.py and requirements.txt for pypi package for opni-proto

---

pkg/bootstrap/client_test.go
pkg/bootstrap/server.go
pkg/util/generic.go

Fix race conditions when bootstrapping multiple capabilities at the same time

---

pkg/auth/cluster/cluster.go
pkg/auth/cluster/cluster_test.go
pkg/auth/cluster/timing_test.go
test/e2e/gateway_test.go

Fix memory usage and improve accuracy for cluster auth request timing test

---

packages/opni/opni/charts/templates/rbac.yaml

Update job permissions in cluster role

---

.drone.yml

Add base images back to drone
Fixes #346

Build base images in drone

---

pkg/logger/logger.go
pkg/plugins/client.go
pkg/plugins/loader.go

Write logs to stderr instead of stdout; fix plugin stderr syncing

---

pkg/slo/query/collectors.go
pkg/slo/query/def.go
pkg/test/environment.go
plugins/slo/pkg/slo/api.go
plugins/slo/pkg/slo/impl.go
plugins/slo/pkg/slo/interfaces.go
plugins/slo/pkg/slo/store.go
plugins/slo/pkg/slo/system.go
test/plugins/slo/slo_test.go

- Datarace will never cause any bugs in functionality, since the map is being **set** non-atomically to a value, but can cause the tests & compiler to complain & fail
- basically wasn't handling the cortex rule CRUD errors before updating the K,V store

Fix slo startup datarace & cluster disconnect

---

pkg/plugins/loader.go

Filter duplicate filenames when searching for plugins with multiple patterns

---

pkg/auth/cluster/timing_test.go

also reduces number of samples per case from 100K to 50K

alternate timing test cases within each thread to reduce effects of environmental interference

---

pkg/agent/agent.go
pkg/apis/alerting/v1alpha/alerting.pb.go
pkg/auth/openid/openid.go
pkg/config/v1beta1/gateway_config.go
pkg/gateway/extensions.go
pkg/gateway/gateway.go
pkg/gateway/grpc.go
pkg/gateway/http.go
pkg/gateway/metrics.go
pkg/gateway/stream.go
pkg/machinery/noauth.go
pkg/management/extensions.go
pkg/management/server.go
pkg/management/server_test.go
pkg/noauth/server.go
pkg/noauth/server_test.go
pkg/opni/commands/gateway.go
pkg/plugins/apis/system/plugin.go
pkg/realtime/server.go
pkg/test/environment.go
pkg/test/plugin.go
pkg/test/unary.go
pkg/util/servers.go
pkg/util/waitctx/context.go
pkg/webui/webui.go
plugins/example/main.go
plugins/example/pkg/example/plugin.go
test/plugins/alerting/alerting_general_test.go

Refactor server lifecycle and reload logic

---

pkg/management/server.go
pkg/opni/commands/agent.go
pkg/resources/dataprepper/workloads.go
plugins/logging/pkg/logging/plugin.go

Strip tcp from listen address

---

magefile.go
packages/opni/opni/charts/crds/crds.yaml

Add generatecrd command to mage

---

packages/opni/opni/charts/templates/ai/longhornmodel.yaml
packages/opni/opni/charts/templates/ai/opnicluster.yaml

This PR adds the spec for the Longhorn model.

Add spec for Longhorn logs model

---

go.mod
go.sum
infra/main.go
packages/opni-agent/opni-agent/charts/templates/agent-config.yaml
packages/opni-agent/opni-agent/charts/values.yaml
pkg/agent/agent.go
pkg/agent/rules.go
pkg/apis/core/v1/extensions.go
pkg/config/v1beta1/agent_config.go
pkg/logger/gin.go
pkg/opni/commands/agent.go
pkg/opni/commands/clusters.go
pkg/resources/monitoring/cortex/config.go
pkg/test/environment.go
pkg/util/notifier/notifier.go

Also adds agent pprof config option
Closes #517 and #502

Fix agent rule sync

---

pkg/resources/gateway/rbac.go
plugins/logging/pkg/logging/admin.go

Fixes RBAC and returns from the logging management API

Fix issues with logging

---

.drone.yml
ci.cue

Closes https://github.com/rancher/opni/issues/617

Push oci images to ghcr.io

---

plugins/logging/pkg/agent/node.go
plugins/logging/pkg/backend/sync.go
plugins/metrics/pkg/agent/node.go
plugins/metrics/pkg/backend/metrics.go

Fix node sync loop

---

aiops/apis/opni_proto/log_anomaly_payload.proto
aiops/apis/setup.py

This PR introduces modification to the opni_proto library by introducing additional fields for workload log identification.

Update opni_proto pypi library to include workload information

---

pkg/apis/alerting/v1/validate.go

email smarthost validation message improvement

---

plugins/logging/pkg/gateway/admin.go

Make opensearch not found pending for status

---

ci.cue
pkg/resources/multiclusterrolebinding/settings.go
pkg/util/opensearch/types/ingest_pipeline_types.go

Update opensearch plugin config

---

pkg/opni/commands/admin_logging.go
pkg/opni/commands/logging.go
pkg/opni/commands/setup_logging.go
pkg/plugins/apis/apiextensions/stream/plugin.go
plugins/logging/pkg/apis/loggingadmin/client.go

Add CLI commands for upgrading Opensearch

---

internal/cortex/cortex_main.go
pkg/resources/monitoring/cortex/config.go

Co-authored-by: Alexandre Lamarre <alexandre.lamarre@suse.com>
Co-authored-by: Joe Kralicky <joe.kralicky@suse.com>

Fix fs storage with all-in-one cortex

---

apis/logging/v1beta1/defaults.go
ci.cue
packages/opni-agent/opni-agent/charts/Chart.yaml
packages/opni-agent/opni-agent/charts/values.yaml
packages/opni-agent/opni-agent/package.yaml
packages/opni/opni/charts/Chart.yaml
packages/opni/opni/package.yaml
pkg/resources/opniopensearch/resources.go
plugins/logging/pkg/gateway/admin.go
plugins/logging/pkg/gateway/plugin_test.go

Disable PSPs in logging

---

packages/opni/opni/charts/questions.yaml

Fix grafana docs url in questions.yaml

---

go.mod
go.sum
pkg/gateway/http.go
pkg/storage/conformance/cluster_store.go
pkg/storage/conformance/rbac_store.go
pkg/storage/crds/rbac_store.go
pkg/storage/errors.go
pkg/storage/etcd/cluster_store.go
pkg/storage/etcd/rbac_store.go
pkg/storage/jetstream/cluster_store.go
pkg/storage/jetstream/jetstream.go
pkg/storage/jetstream/rbac_store.go
test/integration/managementapi/managementapi_rolebindings_test.go
test/integration/managementapi/managementapi_roles_test.go
test/integration/managementapi/managementapi_user_access_test.go

Fix inconsistent create semantics between storage providers, and ensure all create operations are not idempotent

Fix inconsistent create semantics between storage providers

---

ci.cue
packages/opni-agent/opni-agent/charts/Chart.yaml
packages/opni-agent/opni-agent/package.yaml
packages/opni/opni/charts/Chart.yaml
packages/opni/opni/package.yaml
pkg/resources/opniopensearch/resources.go
plugins/logging/pkg/gateway/admin.go
plugins/logging/pkg/gateway/plugin_test.go

Leaving plugin version at 0.7.0-rc1 for the new rc

Chore: update version for 0.7.0-rc2 release

---

pkg/apis/alerting/v1/alerting.pb.go
pkg/apis/alerting/v1/alerting.proto
pkg/apis/alerting/v1/extensions.go
pkg/apis/alerting/v1/validate.go
plugins/alerting/pkg/alerting/api_conditions.go
plugins/alerting/pkg/alerting/util.go
plugins/alerting/pkg/apis/server/condition/alerting.condition.pb.go
plugins/alerting/pkg/apis/server/condition/alerting.condition.pb.gw.go
plugins/alerting/pkg/apis/server/condition/alerting.condition.proto
plugins/alerting/pkg/apis/server/condition/alerting.condition_grpc.pb.go

clone api for Alarms

---

plugins/logging/pkg/errors/errors.go
plugins/logging/pkg/gateway/admin_v2.go

Validate admin v2 input contains data nodes

---

plugins/aiops/pkg/gateway/modeltraining.go

This PR checks to see if a key exists in Nats kv and if it doesn't it will handle the error and return the model status and empty statistics object instead of returning an error.

Fix model status

---

pkg/opensearch/certs/k8s_cert_manager.go

Add retry for fetching client certs.

---

vale.md

add instructions for using `vale` with docker

Add instructions for runnning vale via docker

---

enhancements/aiops/20230203-anomaly-keyword-filter.md

Updates the OEP for filtering out anomalous keywords by including an idea for filtering out the OOM keyword going forward.

Update Oep for anomaly keyword filter

---

pkg/agent/v2/agent.go
pkg/config/v1beta1/agent_config.go
pkg/config/v1beta1/gateway_config.go
pkg/keyring/ephemeral.go
pkg/keyring/keyring.go
pkg/keyring/keyring_test.go
pkg/machinery/keys.go

Closes https://github.com/rancher/opni/issues/1037

Add ephemeral key type, config, and loading machinery

---

plugins/logging/pkg/agent/plugin.go
plugins/logging/pkg/gateway/drivers/kubernetes_manager.go
plugins/logging/pkg/gateway/plugin.go
plugins/logging/pkg/util/otel.go

Instantiate cluster driver in logging plugin

---

apis/logging/v1beta1/logadapter_webhook.go
plugins/logging/pkg/agent/stream.go
plugins/logging/pkg/gateway/plugin.go

Update logging images and fix gRPC impl for agent

Various fixes for logging

---

go.mod
go.sum
pkg/caching/caching.go
pkg/storage/stores.go
pkg/test/testgrpc/cached_server.go
pkg/util/http.go
pkg/util/http_test.go

Implement http caching transport

---

pkg/test/test_cluster_driver.go
pkg/util/http_test.go

Closes #1184 
Added some diagnostics for #1185.

alerting tests data race fix

---

pkg/resources/collector/templates.go

Remove filename from k8s pod logs

---

pkg/resources/collector/templates.go
pkg/resources/collector/workloads.go

Add static pod labels

---

infra/config.go
infra/main.go
infra/pkg/aws/aws.go
infra/pkg/aws/kubernetes.go

- pulumi sdk updates
- fix nginx chart
- add config options to control prometheus crd chart deployment
Supersedes https://github.com/rancher/opni/pull/1151

Pulumi sdk updates

---

go.mod
go.sum

https://github.com/kralicky/totem/commit/4cd02ff95794dbc18713b38150cae7f120b3b695
Fixes https://github.com/rancher/opni/issues/1243

Update totem to apply fix for otelgrpc inject/extract memory leak

---

enhancements/monitoring/20230328-cortex-config-options.md

https://github.com/rancher/opni/issues/1262

OEP: Cortex Config Options

---

plugins/aiops/pkg/gateway/modeltraining.go

The AIOps plugin has been updated to enable AI services when a training job is submitted. This PR addresses https://github.com/rancher/opni/issues/1147

Update AIOps plugin to enable AI services when training job is submitted

---

plugins/aiops/pkg/gateway/modeltraining.go

This PR updates the ModelTraining plugin to use the defined struct to fetch the latest workload parameters from KV.

Address training parameter fix

---

infra/pkg/aws/kubernetes.go

Fixes https://github.com/rancher/opni/issues/1301

infra: update nginx-ingress-controller service name

---

go.mod
go.sum
pkg/gateway/gateway.go
pkg/gateway/stream.go
pkg/management/collector.go
pkg/plugins/apis/apiextensions/stream/plugin.go
pkg/test/environment.go
test/integration/gateway/impersonated_metrics_test.go
test/plugins/metrics/metrics_suite_test.go

Fixes https://github.com/rancher/opni/issues/1295

Fix duplicate metrics registration causing scrape errors

---

plugins/alerting/pkg/alerting/condition_handlers.go
plugins/alerting/pkg/alerting/drivers/cluster_driver.go
plugins/alerting/pkg/alerting/impl.go
plugins/alerting/pkg/alerting/plugin.go
plugins/alerting/pkg/alerting/sync.go
plugins/alerting/pkg/alerting/system.go

Fix alerting condition evalutation triggers

---

packages/opni/opni/charts/templates/gateway.yaml
pkg/resources/gateway/alerting.go
plugins/alerting/pkg/alerting/drivers/alerting_manager/cluster_driver.go
plugins/alerting/pkg/alerting/drivers/alerting_manager/helpers.go

Fix HA replicas in Alerting Cluster

---

packages/opni-agent/opni-agent/package.yaml

Remove the CRD charts from the agent

Remove crd chart from agent

---

pkg/resources/multiclusterrolebinding/settings.go
plugins/logging/pkg/opensearchdata/admin.go
plugins/logging/pkg/opensearchdata/delete.go
plugins/logging/pkg/opensearchdata/opensearchdata.go

Fix delete of old Opensearch data

---

pkg/apis/management/v1/extensions.go
pkg/opni/commands/debug.go
pkg/opni/commands/keyrings.go
test/e2e/gateway_test.go

Fixes https://github.com/rancher/opni/issues/1387
Closes https://github.com/rancher/opni/issues/1388

Agent import debug command + CLI config loading fixes

---

plugins/metrics/pkg/agent/runner.go
test/plugins/metrics/metrics_suite_test.go
test/plugins/metrics/runner_test.go
test/plugins/metrics/utils_test.go

Improves how we handle errors in the data import.
closes #1391 
closes #1373

Import error

---

pkg/resources/preprocessor/workloads.go

Prefill log type and component

---

plugins/metrics/pkg/backend/ops.go

Update metrics capability uninstall error message

---

packages/opni-agent/kube-prometheus-stack/package.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-alertmanagerconfigs.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-alertmanagers.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-podmonitors.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-probes.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-prometheuses.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-prometheusrules.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-servicemonitors.yaml
packages/opni/opni-prometheus-crd/charts/templates/crd-thanosrulers.yaml

Update kube-prometheus-stack subchart and prometheus crds

---

pkg/otel/templates/metrics.tmpl
plugins/metrics/pkg/agent/drivers/opni_manager_otel/otel_driver.go

Fix release bugs

---

pkg/resources/monitoring/dashboards/opni-gateway.json
pkg/resources/monitoring/dashboards/opni-service-latency.json
pkg/resources/monitoring/grafana.go

Fixes https://github.com/rancher/opni/issues/1333

Home dashboard bugfixes; add new service latency dashboard

---

pkg/agent/v2/agent.go
pkg/opni/commands/agent_v2.go
pkg/test/environment.go
test/integration/agent_bootstrap_test.go

Fixes https://github.com/rancher/opni/issues/1442

Fix agent startup error when missing bootstrap config but bootstrap is not required

---

pkg/resources/monitoring/dashboards/home.json

These changes were accidentally left out of https://github.com/rancher/opni/pull/1453

Fix queries in home dashboard

---

pkg/resources/preprocessor/workloads.go

Minor fix to the log preprocessing

Update transform context

---

pkg/opni/commands/client.go

Only create prometheus crds if they don't exist

---

pkg/resources/gateway/servicemonitor.go
pkg/resources/monitoring/dashboards/home.json
pkg/resources/monitoring/dashboards/opni-service-latency.json

* Dashboard query fixes
* Add event marker to show node reboots
* Set HonorLabels option for gateway scrape endpoint to ensure consistency between otel and prometheus

Dashboard query fixes

---

plugins/logging/pkg/backend/install.go
plugins/logging/pkg/backend/logging.go
plugins/logging/pkg/backend/metadata.go
plugins/logging/pkg/gateway/drivers/backend/cluster_driver.go
plugins/logging/pkg/gateway/drivers/backend/kubernetes_manager/kubernetes_manager.go
plugins/logging/test/test_drivers.go

Add cluster metadata on install

---

internal/cmd/testenv/main.go
pkg/test/testdata/testdata/cortex/config.yaml
plugins/alerting/pkg/alerting/system.go
plugins/slo/pkg/apis/slo/validate.go
plugins/slo/pkg/slo/impl.go
plugins/slo/pkg/slo/simple.go
plugins/slo/pkg/slo/slo_suite_test.go
plugins/slo/pkg/slo/slo_test.go
plugins/slo/pkg/slo/system.go
plugins/slo/test/test_plugin.go
test/plugins/slo/slo_suite_test.go
test/plugins/slo/slo_test.go

Tech debt : SLO test fixes

---

web/package.json
web/pkg/opni/formatters/StatusBadge.vue
web/yarn.lock

https://github.com/rancher/opni/issues/1492

Adding the tooltip back to the StatusBadge formatter

---

web/pkg/opni/components/AlertingBackend.vue
web/pkg/opni/components/Radio/RadioButton.vue
web/pkg/opni/components/Radio/RadioGroup.vue

- I had to modify the default implementation of radio group in order to display tooltips. I'll try to get this merged into rancher/shell.
https://github.com/rancher/opni/issues/1530

Switching over to radio buttons for Alerting mode

---

Tiltfile
dagger/x/main.go
magefiles/targets/test.go
pkg/management/extensions_test.go

- Fix flaky helm_resource Tiltfile
- Fix testbin edge case hang
-  Fix http apiextension test flake

Update Tiltfile with new build system + minor fixes

---

web/pkg/opni/components/AlertingOverview.vue
web/pkg/opni/models/alerting/Condition.ts
web/pkg/opni/utils/requests/alerts.ts

I'm showing two successful and one failed request to show what happens in each scenario.
https://github.com/rancher/opni/assets/55104481/2c00c047-e928-464e-bed2-6c503587d92d
https://github.com/rancher/opni/issues/1352
https://github.com/rancher/opni/issues/1524

Updating the alert overview to include more information when hovering  over an event

---

plugins/alerting/pkg/alerting/alarms/v1/streams.go
plugins/alerting/pkg/alerting/management.go

Agent disconnect alarm enhancement

---

pkg/oci/kubernetes/images.go
pkg/oci/kubernetes/kubernetes.go
pkg/oci/kubernetes/kubernetes_test.go
pkg/oci/oci.go
pkg/oci/oci_test.go
pkg/update/kubernetes/client/client.go
pkg/update/kubernetes/client/suite_test.go
pkg/update/kubernetes/server/server.go
pkg/update/kubernetes/server/suite_test.go
pkg/update/suite_test.go

Fixes https://github.com/rancher/opni/issues/1573

Fix minimal image ref format inconsistencies in image update logic

---

dagger/images/images.go
dagger/main.go
go.mod
go.sum
internal/linter/linter.go
pkg/apis/core/v1/validation.go
pkg/test/environment.go
plugins/alerting/pkg/alerting/management.go
plugins/alerting/pkg/alerting/system.go
plugins/slo/pkg/slo/system.go
test/integration/managementapi_rolebindings_test.go
test/web/agents_test.go
test/web/monitoring_test.go
test/web/web_suite_test.go
web/pkg/opni/components/MonitoringBackend/index.vue
web/pkg/opni/formatters/StatusBadge.vue
web/pkg/opni/models/Capability.ts

This PR adds automated tests for the admin dashboard using https://github.com/onsi/biloba.
Includes tests for agents, as well as the tests listed in the monitoring release checklist: https://github.com/rancher/opni/wiki/Release-Checklist

Dashboard test suite

---

pkg/opni/commands/import_progress.go

Fix import progress timestamp

---

pkg/supportagent/shipper/otlp.go

Fix up missing attribute

---

internal/alerting/alertmanager/alertmanager_main.go
pkg/alerting/drivers/config/message.go
pkg/alerting/extensions/api.go
pkg/alerting/extensions/destination/destination.go
pkg/alerting/extensions/destination/k8s.go
pkg/alerting/extensions/embedded_server.go
pkg/alerting/extensions/embedded_server_test.go
pkg/resources/alerting/base.go
pkg/resources/gateway/rbac.go
pkg/test/environment.go

Configures the Alertmanager instance to publish opni alerts to kubernetes events
Closes #1544

send alerts to k8s events

---

plugins/aiops/pkg/gateway/admin.go

This PR updates the path of the pretrained models as they have been moved to the updated AWS account.

Update paths of pretrained models

---

pkg/update/patch/client/client.go

Add uint64 cast to Stat_t.Dev for arm64 compilation

---

pkg/util/errors.go
plugins/alerting/pkg/alerting/admin.go
plugins/alerting/pkg/alerting/alarms/v1/component.go
plugins/alerting/pkg/alerting/alarms/v1/teardown.go
plugins/alerting/pkg/alerting/plugin.go

Closes https://github.com/rancher/opni/issues/1620
Addresses a subset of scenarios that cause https://github.com/rancher/opni/issues/1621 / https://github.com/rancher/opni/issues/1583

Fix blocking sync issues

---

pkg/resources/opniopensearch/resources.go
plugins/logging/pkg/gateway/drivers/management/kubernetes_manager/kubernetes_manager.go

Fix issues with Opensearch upgrades

---

pkg/resources/opniopensearch/resources.go

This PR ensures the logic includes prerelease versions

Fix version constraint

---

web/pkg/opni/components/AlertingOverview.vue
web/pkg/opni/components/Main.vue

Action menu fix:
This is actually a bug in the rancher code and not something that can be fixed there and make it into opni quickly. The code there isn't capable of accounting for page scrolling correctly since in Rancher an element scrolls instead of the entire page. I've made it so the opni layout will now have an element scroll instead of the entire page which masks the issue in the same way rancher does.
https://github.com/rancher/opni/assets/55104481/7cac4f0a-48a7-4490-a9c2-39292614401c
Show errors in the alert overview:
Now account for requests failing and not just empty responses
https://github.com/rancher/opni/assets/55104481/51c4b5ec-6b80-4c48-966a-4b78f040c247

Fixing action-menu position and show errors in the alert overview

---

pkg/apis/alerting/v1/validate.go
plugins/alerting/main.go
plugins/alerting/pkg/agent/drivers/default_driver/driver.go
plugins/alerting/pkg/agent/plugin.go
plugins/alerting/pkg/agent/rules.go
plugins/alerting/pkg/alerting/alarms/v1/rules_sync.go
plugins/alerting/pkg/alerting/alarms/v1/server.go
plugins/alerting/test/test_drivers.go
plugins/alerting/test/test_plugin.go
test/plugins/alerting/capability_test.go
test/plugins/slo/slo_test.go

- make sure the rule sync driver is loaded correctly, a couple of test improvements

Implement rule sync driver correctly

---

pkg/auth/cluster/v2/authv2_test.go

Closes https://github.com/rancher/opni/issues/1645

Auth test fix

---

dagger/ci/defaults.toml
dagger/helm/push.go

- Allow overriding the oci chart repo name
- Fix oci charts pushing to the wrong repo

OCI chart repo fixes

---

web/pkg/opni/components/Alarm/AgentDisconnect.vue
web/pkg/opni/components/Alarm/DownstreamCapability.vue
web/pkg/opni/components/Alarm/KubeState.vue
web/pkg/opni/components/Alarm/MonitoringBackend.vue
web/pkg/opni/components/Alarm/Prometheus.vue
web/pkg/opni/components/Alarm/index.vue
web/pkg/opni/components/Alarms.vue
web/pkg/opni/components/AlertingOverview.vue
web/pkg/opni/components/ConditionFilter.vue
web/pkg/opni/components/LoadingSpinner.vue
web/pkg/opni/components/LoadingSpinnerOverlay.vue
web/pkg/opni/components/Main.vue
web/pkg/opni/models/alerting/Condition.ts
web/pkg/opni/utils/alarms.ts
web/pkg/opni/utils/requests/alerts.ts

https://github.com/rancher/opni/issues/1529
https://github.com/rancher/opni/assets/55104481/9735c710-4c66-4633-a9c1-4a665a038d24

Add more filtering to alerting

---

plugins/metrics/pkg/agent/drivers/opni_manager_otel/otel_driver.go

Correctly retry otel collector reconciliation

---

pkg/alerting/drivers/config/conversion.go
pkg/alerting/drivers/config/receiver.go
pkg/apis/alerting/v1/secrets.go
pkg/apis/alerting/v1/unit_test.go
pkg/apis/alerting/v1/validate.go
plugins/alerting/pkg/alerting/endpoints/v1/server.go
test/plugins/alerting/alerting_test.go

Improve webhook endpoint validation

---

web/pkg/opni/components/AiOpsBackend.vue
web/pkg/opni/components/AiOpsPretrained.vue
web/pkg/opni/components/Alarm/index.vue
web/pkg/opni/components/AttachedEndpoints.vue
web/pkg/opni/components/Endpoint/Auths/Authorization.vue
web/pkg/opni/components/Endpoint/Auths/BasicAuth.vue
web/pkg/opni/components/Endpoint/Auths/OAuth2.vue
web/pkg/opni/components/Endpoint/Email.vue
web/pkg/opni/components/Endpoint/PagerDuty.vue
web/pkg/opni/components/Endpoint/Slack.vue
web/pkg/opni/components/Endpoint/Tls.vue
web/pkg/opni/components/Endpoint/Webhook.vue
web/pkg/opni/components/Endpoint/index.vue
web/pkg/opni/components/LogAnomalyBackend.vue
web/pkg/opni/components/MetricFilter.vue
web/pkg/opni/components/PretrainedModels.vue
web/pkg/opni/components/SLO.vue
web/pkg/opni/models/alerting/Endpoint.ts
web/pkg/opni/router.js
web/pkg/opni/styles/app.scss
web/pkg/opni/styles/global/_layout.scss

https://github.com/rancher/opni/issues/1673
https://github.com/rancher/opni/assets/55104481/e422838b-839e-4ed7-a1a8-a8ba8baec22b
Updated organization:

Adding the webhook endpoint to alerting

---

go.mod
go.sum
plugins/logging/pkg/errors/errors.go
plugins/logging/pkg/gateway/admin_v2.go

Various logging fixes

---

plugins/alerting/pkg/alerting/alarms/v1/streams.go

Closes https://github.com/rancher/opni/issues/1719

Fix nil status handling in cortex status api

---

pkg/clients/gateway_client.go

Fixes https://github.com/rancher/opni/issues/1737

Fix possible race condition on grpc header metadata during gateway client connection

---

web/pkg/opni/index.ts
web/vue.config.js

Adding a commit hash to the console of the UI to make debugging easier

---

web/pkg/opni/index.ts
web/vue.config.js

Revert "Adding a commit hash to the console of the UI to make debugging easier"

---

web/pkg/opni/components/AlertingOverview.vue

https://github.com/rancher/opni/issues/1757

Fixing overflow issues in alerting overview

---

pkg/storage/crds/value_store.go
pkg/storage/inmemory/value_store.go
pkg/storage/kvutil/kvutil.go
pkg/storage/options.go

(cherry picked from commit ce21f33dd02fb80381d90dd6dfe5704a65ea4267)

(backport) Bugfixes for crd and in-memory value store backends

---

plugins/metrics/pkg/cortex/configutil/config.go

Remove ruler hardcoded filesystem backend

---

pkg/opensearch/reconciler/reconciler.go
plugins/logging/pkg/errors/errors.go
plugins/logging/pkg/gateway/drivers/management/kubernetes_manager/kubernetes_manager.go

Fix nil pointer and verification errors with snapshots

---

web/pkg/opni/components/Backend.vue
web/pkg/opni/components/LogAnomalyBackend.vue
web/pkg/opni/components/Snapshots.vue
web/pkg/opni/components/WorkloadModelConfig.vue
web/pkg/opni/generated/github.com/rancher/opni/pkg/apis/management/v1/management_svc.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/logging/apis/loggingadmin/loggingadmin_svc.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/metrics/apis/cortexadmin/cortexadmin_svc.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/metrics/apis/cortexops/cortexops_svc.ts
web/pkg/opni/models/LoggingAdminV2/SnapshotStatus.ts
web/service-generator/src/index.ts

Fixes:
https://github.com/rancher/opni/issues/1805
https://github.com/rancher/opni/issues/1803
https://github.com/rancher/opni/issues/1808
Logging snapshot issue

Adressing several issues for aiops and logging

---

plugins/aiops/apis/admin/extensions.go
plugins/aiops/pkg/gateway/admin.go
plugins/logging/apis/loggingadmin/extensions.go
plugins/logging/pkg/gateway/admin_v2.go

Related to https://github.com/rancher/opni/issues/1810

Validate incoming S3 configs from the configuration apis

---

web/pkg/opni/components/MonitoringBackend/Storage/Azure.vue
web/pkg/opni/components/MonitoringBackend/Storage/Filesystem.vue
web/pkg/opni/components/MonitoringBackend/Storage/Gcs.vue
web/pkg/opni/components/MonitoringBackend/Storage/S3.vue
web/pkg/opni/components/MonitoringBackend/Storage/Swift.vue
web/pkg/opni/components/MonitoringBackend/Storage/index.vue

Adding the additional storage providers to the monitoring configuration

---

go.mod
infra/go.mod
infra/pkg/aws/aws.go

This reverts commit 5cf0f267abd0ee8ca7b4d1b97f4b40e99077f251.

Revert "bump pulumi sdk; increase node root volume size"
