rancher/opni

src/preprocessing-service/preprocess.py

`t.$date` field is found in RKE control plane logs and is causing bulk indexing issues

Updating preprocessing to remove problematic t.$date field

---

src/k8s/services/nulog-inference-service.yaml

Minio access and secret keys were not properly set for Nulog Inference Service.

Opnictl: Fix bug for Minio access and secret keys for Nulog Inference Service

---

src/dashboard/Kibana/README.md
src/k8s/services/nulog-inference-service-control-plane.yaml
src/models/nulog/NuLogParser.py
src/models/nulog/NuLogTokenizer.py
src/models/nulog/inference.py
src/nulog-inference-service/Dockerfile
src/nulog-inference-service/NulogServer.py
src/nulog-inference-service/start-nulog-inference.py

the nulog workload image and control-plane image now get merged to use the same image
This makes the maintenance easier.
the nulog-CP-service will read from `control-plane-output/` dir with the pre-trained model, while the regular nulog-service (for workload apps) will read from `output/` dir as usual.

merge 2 nulog images into 1

---

controllers/opnidemo_controller.go
pkg/demo/services.go
scripts/quickstart.sh

Updates for the quickstart.  In particular if we start receiving logs before the ISM policy has been applied it causes conflicts in elasticsearch, so we wait for that to be done before applying the logging CRs.
Also updates the kibana dashboard pod definition to include the Kibana endpoint.

Update images, and order CRs

---

pkg/opnictl/commands/create.go
scripts/quickstart.sh

It's easier for the quickstart to expose Kibana as a nodeport service.  Also in the quickstart script we should wait for the user to trigger the anomaly injection

Make kibana nodeport

---

pkg/opnictl/commands/uninstall.go

This fixes an issue where helm charts fail to delete when opni bundles the helm controller, due to the helm controller being deleted before helmcharts, which will prevent finalizers from being run.
Related: https://github.com/k3s-io/k3s/pull/3515

Use foreground deletion propagation when uninstalling opni

---

controllers/demo/opnidemo_controller.go
go.mod
go.sum
pkg/demo/services.go

**what does this PR do:**
as the title implies. the `training-controller` service has been renamed to `gpu-service`, which is now a pod with 2 containers -- `gpu-service-controller` and `gpu-service-worker`. 
- `gpu-service-controller` merged from the old `training-controller`, basically manages both training and inference requests for gpu-service. 
- `gpu-service-worker` is the container that actually owns the GPU, and it executes any requests forward from the controller.
**Dependency:**
these 2 PRs should get merged before this PR. build is failing as the new images aren't existed yet.

update manifests deployments for gpu-service

---

.drone.yml
apis/v1beta1/webhook_suite_test.go
controllers/demo/opnidemo_controller_test.go
controllers/demo/suite_test.go
controllers/logadapter_controller_test.go
controllers/opnicluster_controller_test.go
controllers/pretrainedmodel_controller_test.go
controllers/suite_test.go
pkg/opnictl/opnictl_suite_test.go
pkg/opnictl/opnictl_test.go
pkg/resources/labels_test.go
pkg/resources/opnicluster/elastic/indices/elasticsearch_reconciler_test.go
pkg/resources/opnicluster/elastic/indices/elasticsearch_suite_test.go
pkg/resources/opnicluster/opnicluster_suite_test.go
pkg/resources/resources_suite_test.go
scripts/e2e
test/e2e/demo_test.go
test/e2e/e2e_suite_test.go

Have separated e2e tests out to a separate outline to help solve resourcing issues.  E2e tests will also only run on the drone-pr instance, and only when a pull-request is opened.
The e2e-test pipeline is dependent on the build pipeline so won't run if previous steps fail.

Separate e2e tests

---

deploy/patches/versions.yaml

Update the version in OpniCluster crd to be 1.1.0 to reflect Opensearch versioning.

Update version of OpniCluster to be 1.1.0

---

plugins/slo/pkg/slo/doc.go
plugins/slo/pkg/slo/generate.go
plugins/slo/pkg/slo/slo_test.go
plugins/slo/pkg/slo/util.go
plugins/slo/pkg/slo/window.go

Fixing sloth in the best way possible : removing sloth (kind of)
Once I started trying to generate alerts with sloth + my custom OpenSLO v1 format IR, I realized using the sloth generators weren't going to work at all for our use-case.
1) they are tied to OO where the methods are predicated on reading from the filesystem
2) Confusing function factories and factory configs which were tied to very specific yaml input formats
In essence, I stripped the sloth generator down to the basics and repurposed the raw core functions into the plugin package `plugins/slo/pkg/slo` so we can have more control over how to generate alerts & recording rules

Fix sloth 

---

magefile.go
pkg/opni/commands/agent.go
pkg/opni/commands/manager.go
pkg/opni/commands/version.go
pkg/opni/common/options.go
pkg/opni/root.go
pkg/util/manager/upgrade_requester.go

PR make the following changes:
- Removed the dirty repo checks for versioning because they fail when running in the dagger environment.
- Moved disable usage to a global persistent flag.
- Added upgrade responder to the agent, and added extra info to differentiate the two.
Fixes #392

Fix upgrade responder and add extra info

---

.drone.yml

This PR updates the publish version tag for the opni-opensearch-update-service image for RC 6.

Update publish version tag for opensearch updating service image

---

pkg/resources/gateway/configmap.go

in `resources/gateway/configmap.go`, need to check for r.gw.Spec.Alerting is nil, since we decided to specify that part of the spec as optional (and therefore as a pointer)

Check for nil pointer in gw.Spec.Alerting

---

config/manager/manager.yaml
pkg/resources/gateway/alerting.go
pkg/resources/gateway/deployment.go
plugins/logging/pkg/logging/plugin.go

couple of `OPNI_SYSTEM_NAMESPACE` env var were still in use, when  we made the change for opni-manager to use `POD_NAMESPACE` they were leftover
See https://github.com/rancher/opni/pull/327 & https://github.com/rancher/opni/issues/317

Fix reconciler error with correct ns name

---

pkg/capabilities/store.go
pkg/capabilities/store_test.go
pkg/capabilities/template.go
pkg/gateway/gateway.go
plugins/cortex/pkg/cortex/capability.go

- Update monitoring installer template to allow hostname and port override options in the UI
- Allow one level of installer template recursion
Closes #408

Update monitoring installer template

---

pkg/auth/cluster/timing_test.go

Bumping the threshold from 0.15->0.2. This may require additional adjustments, cloud ci runners are rather unpredictable.

adjust ks-test threshold in ci

---

aiops/opni-opensearch-update-service/opensearch-update-service/app/main.py
pkg/resources/opnicluster/elastic/indices/indices.go
pkg/resources/opnicluster/elastic/indices/opni_settings.go

This PR adds logic to the Opensearch Updating Service by creating the templates index which stores the template, the template cluster ID as well as the most frequently occurring log message associated with that template. It receives this information through the Opni DRAIN service.

Opensearch template index

---

go.mod
go.sum

Includes a fix for the bug which was causing the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x38758da]
goroutine 12206 [running]:
github.com/rancher/opni/pkg/apis/control/v1.(*healthClient).GetHealth(0xc0072b3d90, {0x7aa6998, 0xc0078a9f20}, 0x0?, {0x0, 0x0, 0x0})
/src/pkg/apis/control/v1/remote_grpc.pb.go:40 +0x9a
github.com/rancher/opni/pkg/health.(*Listener).HandleConnection(0xc0003686c0, {0x7aa6998, 0xc0078a9f20}, {0x7f07a4287ed8, 0xc006ed6c00})
/src/pkg/health/listener.go:209 +0x69c
github.com/rancher/opni/pkg/health.(*Listener).HandleAgentConnection(0x1?, {0x7aa6998, 0xc0078a9f20}, {0x7a843a8?, 0xc006ed6c00})
/src/pkg/health/listener.go:360 +
```

Upgrade totem to v1.1.0-rc6

---

plugins/logging/pkg/agent/drivers/kubernetes/kubernetes_manager.go
plugins/logging/pkg/agent/node.go

If the backend doesn't exist then the opensearchConfig object will be nil.  In this case we should just create the objects with meta data so the reconcileObject function can delete them.
Fixes #697 
@AmartC FYI

Tidy up nil pointer on removal

---

go.mod
go.sum
pkg/agent/v2/agent.go
pkg/apis/control/v1/msg.go
pkg/patch/cache.go
pkg/patch/server.go

Old performance estimate (4 plugins = 25MB *2):
New performance estimate (5 plugins = 30MB *2):
- re-arranging some file operations
- stream buffered io

Some Naive optimizations for agent memory patch performance + PatchOp_REMOVE bug fixes

---

controllers/ai_opnicluster_controller_test.go
pkg/resources/opnicluster/services.go

This PR sets the CPU inferencing service to use 0.7 as the threshold to be consistent with the GPU inferencing service.

Fix up cpu inferencing service to also use 0.7 threshold for inferencing

---

plugins/aiops/pkg/gateway/modeltraining.go

This PR resets the training statistics for a model when a new training job is submitted.

Have training plugin reset statistics for next model

---

pkg/resources/opnicluster/services.go

This PR addresses a bug in the RC where workload drain services were not being enabled correctly.

Update services.go for enabling workload DRAIN service with GPU services

---

go.mod
go.sum
pkg/storage/jetstream/cluster_store.go
pkg/storage/jetstream/jetstream.go
pkg/storage/jetstream/rbac_store.go

A fix for https://github.com/nats-io/nats.go/issues/1134 was recently merged, so we can remove our workaround.

Update nats error checking logic to use new exported error type

---

pkg/patch/client.go
pkg/patch/client_test.go
pkg/test/fs.go

Ensure patch client temp directory is created on the same device as the plugin directory to prevent cross-device rename errors.

Ensure patch client temp directory is created on the same device as the plugin directory

---

go.mod
pkg/test/environment.go
plugins/logging/pkg/gateway/admin_v2.go
plugins/logging/pkg/gateway/admin_v2_test.go
plugins/logging/pkg/gateway/drivers/kubernetes_manager.go
plugins/logging/pkg/gateway/opensearch.go
plugins/logging/pkg/gateway/plugin.go
plugins/logging/pkg/gateway/suite_test.go
plugins/logging/pkg/opensearchdata/admin.go
plugins/logging/pkg/opensearchdata/opensearchdata.go

This will ensure that if the gateway is restarted before the opensearch admin user is successfully created the creation of the admin user will be picked up again.
Fixes #930

Add state tracking to admin creation

---

plugins/alerting/pkg/alerting/drivers/alerting_driver_cluster.go
plugins/alerting/pkg/alerting/drivers/alerting_driver_helpers.go

when uninstalling the alerting cluster, unset configurable fields.
When the configurable fields are unset, it uses the defaults on the subsequent install. The UI handles applying configuration from users.

fix alerting install conflict by unsetting fields in uninstall

---

pkg/opni/commands/completion.go
pkg/opni/commands/completion_plugins.go
pkg/opni/commands/import_progress.go

There were some missing `//go:build !noplugins` build constraints in files related to the recent [ETL tool PR](https://github.com/rancher/opni/pull/1014)

fix minimal build issue

---

pkg/alerting/drivers/cortex/cortex.go
pkg/resources/monitoring/cortex/config.go
plugins/alerting/pkg/alerting/condition_handlers.go

Metrics path writes to a separate path in the routing logic, when we should have opni created metrics conditions written to their namespaced paths like non-metrics conditions.

Fix metrics label paths for use with opni alerting

---

pkg/opni/commands/import.go
plugins/metrics/pkg/agent/node.go

Running `opni import discover` without a namespace filter causes `nil pointer dereference`. This PR resolves that oversight.

fix issue with nil namespace in discovery request

---

plugins/alerting/pkg/alerting/api_conditions.go

Check the full list of capabilities when determining if metrics is installed for evaluating metric alarm status health.

check all installed capabilites in alarm status

---

plugins/aiops/pkg/gateway/aggregation.go

This PR updates the Opensearch query by aggregating on the field "namespace_name" instead of "kubernetes.namespace_name"
Addresses https://github.com/rancher/opni/issues/1180

Update opensearch query for getting log counts by deployment

---

aiops/requirements.txt
images/python/requirements.txt
plugins/aiops/pkg/gateway/aggregation.go
plugins/aiops/pkg/gateway/modeltraining.go
plugins/aiops/pkg/gateway/plugin.go

This PR updates the AIOps gateway plugin to use the Nats kv feature for keeping track of the model training parameters. It also introduces separate KV buckets, os-workload-aggregation, model-training-parameters and model-training-statistics to keep track of different usages of kv storage.
Addresses https://github.com/rancher/opni/issues/1148

Update AIOps gateway plugin to use Nats Jetstream KV storage for storing model training parameters

---

pkg/resources/gateway/deployment.go

When the replacement gateway pod is scheduled to the same node the replacement will fail because the gateway uses a RWO PersistentVolume.  To avoid this the rollout strategy should be recreate.
This means that the gateway won't be highly available, so this will need to be revisited when we work on making it HA.  As part of this work the plugin cache will need to be reworked to avoid using a RWO volume.
Fixes #1209

Switch gateway to recreate deployment

---

apis/monitoring/v1beta1/prometheus_types.go
pkg/opni/commands/client.go

This will allow users who want to use opentelemetry to not have to install the prometheus operator.

Add prometheus CRD to auto install

---

go.mod
go.sum
packages/opni-agent/opni-agent/charts/templates/statefulset_v2.yaml
packages/opni-agent/opni-agent/charts/values.yaml
packages/opni/opni/charts/templates/nats.yaml
packages/opni/opni/charts/values.yaml

Add storage class option and fix IntOrStr

---

plugins/logging/pkg/gateway/admin_v2.go
plugins/logging/pkg/opensearchdata/opensearchdata.go
plugins/logging/pkg/opensearchdata/status.go
plugins/logging/pkg/util/opensearch.go

Return opensearch status immediately

---

plugins/metrics/pkg/agent/drivers/prometheus_operator/external_operator.go

Fixes https://github.com/rancher/opni/issues/1469
This appears to be the only field causing issues from the missing defaults in the wrangler-generated Prometheus CRD.

Add default evaluation interval field to prometheus spec

---

pkg/resources/preprocessor/workloads.go

It seems like there have been some changes to timestamp storage for log documents.  This configures some additional options to control how we store timestamps.

Update config for event shipping

---

test/integration/managementapi_rolebindings_test.go
test/integration/managementapi_roles_test.go

Since #1336 added new validations for roles and role bindings, this causes two tests intended to test 404s to error out with Invalid Argument instead of Not Found. Added the missing fields here

Update role and rb tests for validations

---

pkg/apis/core/v1/labels.go
pkg/crypto/xof.go
pkg/opni/commands/manager.go
pkg/opni/commands/support.go
pkg/opni/commands/tokens.go
pkg/supportagent/config/supportagent.go
pkg/supportagent/metadata.go
plugins/logging/pkg/backend/install.go
plugins/logging/pkg/errors/errors.go
plugins/logging/pkg/gateway/drivers/backend/cluster_driver.go
plugins/logging/pkg/gateway/drivers/backend/kubernetes_manager/kubernetes_manager.go
plugins/logging/test/test_drivers.go

This PR does the following things:
- Adds a well known Opni label to designate a cluster is actually a support user
- Creates a user account for Opensearch when the logging capability is added to a support user
- Generates the password for that account ratcheted off the client key
- Adds a command to the support CLI to display the generated password.
Fixes #1568

Add support label and role creation

---

web/pkg/opni/utils/requests/node-configuration.ts

This is causing a ton of extra overhead from an experimental feature with otel metrics that is not production ready yet

Fix open telemetry config from UI

---

pkg/agent/v2/agent.go
pkg/opni/commands/gateway.go
pkg/opni/commands/support.go
pkg/update/syncer.go

Moves the update syncer and exports it to make it reusable. 
Add noop updater to the support plugin.

Add noop updates for support agent

---

pkg/config/v1beta1/gateway_config.go
pkg/update/patch/patcher.go
pkg/update/patch/server/server.go
pkg/update/patch/server/server_suite_test.go
pkg/update/patch/server/server_test.go

Add new zstd dictionary-based patch engine. It is significantly faster and less computationally expensive than bsdiff, with the tradeoff of slightly larger patches.
Will eventually make it the default option, but not yet.

Add new zstd dictionary-based patch engine

---

.gitignore
pkg/storage/etcd/etcd_suite_test.go
pkg/storage/etcd/lock.go
pkg/storage/etcd/lock_manager.go
pkg/storage/lock/lock.go
pkg/storage/lock/lock_suite_test.go
pkg/storage/lock/lock_test.go
pkg/storage/stores.go
pkg/test/benchmark/storage/lock_bench.go
pkg/test/benchmark/storage/storage_suite_test.go
pkg/test/conformance/storage/lock_helpers.go
pkg/test/conformance/storage/lock_manager.go

Includes:
```go
type A struct {
mu sync.Mutex
}
```
should become
```go
type A struct {
mu stores.LockManager
}
```
and NOT
```go
type A struct {
mu stores.Lock
}
```
- Implementation details for the Lock can be injected via `LockOptions`
- `WithKeepalive` : keeps the lock alive as long as the process owning the lock is still running, or unlock is called
- typical usecases: leader election
- `WithExpireDuration` : fallback to set a hard limit on expiry, if we opt-out of keepalive semantics
- typical usecase : transaction or task that requires distributed locking
Does not include a jetstream implementation (yet), due to:
- scalability concerns with the current jetstream version < v2.10
- expiry semantics with jetstream

Distributed lock manager

---

web/pkg/opni/components/Endpoint/Webhook.vue

No longer have TLS or Authorization enabled by default

Changing the default values when creating an Alerting Webhook endpoint

---

packages/opni-agent/opni-agent/charts/templates/deployment.yaml

Fixes #1724
Have removed readiness check as it is redundant with the liveness check.  Behaviour with this PR is as follows:
* On startup agent will wait for up to 5 minutes to become live.  This will give it time to download plugins on a slow network connection
* After startup the container will restart if it becomes unavailable for 30 seconds.

Update agent probes

---

test/web/monitoring_test.go

Fix spec timing out while waiting on a status polling interval that is longer than the eventually timeout

Monitoring web test fix

---

pkg/storage/jetstream/jetstream_suite_test.go
pkg/storage/jetstream/lock.go
pkg/storage/jetstream/lock_manager.go
pkg/test/benchmark/storage/storage_suite_test.go
pkg/test/conformance/storage/lock_manager.go

An exclusive distributed lock implementation with the same liveliness guarantees as the etcd lock. 
Requires nats 2.9+

Jetstream Lock implementation

---

pkg/dashboard/dashboard.go
plugins/alerting/pkg/alerting/alarms/v1/setup.go
plugins/logging/pkg/backend/metadata.go
web/pkg/opni/components/LoggingBackend/index.vue

Cortex config introduced a couple of bugs related to logging:

Logs fixes

---

internal/codegen/cli/extensions.go
internal/codegen/cli/generator.go
plugins/metrics/apis/cortexops/cortexops_cli.pb.go

This improves how field values from nested message literals are rendered as strings for flag set defaults.
---
For example, given:
```proto
message MetricsCapabilitySpec {
.config.v1beta1.RulesSpec rules = 1 [(cli.flag_set).default = {
[type.googleapis.com/config.v1beta1.RulesSpec]: {
discovery: {
prometheusRules: {
searchNamespaces: [""]; // search all namespaces
}
}
}
}];
}
```
The default field above will translate into this call to flagutil.SetDefValue:
```go
func (in *MetricsCapabilitySpec) FlagSet(prefix ...string) *pflag.FlagSet {
// ...
fs.AddFlagSet(in.Rules.FlagSet(append(prefix, "rules")...))
flagutil.SetDefValue(fs, strings.Join(append(prefix, "rules", "discovery.prometheus-rules.search-namespaces"), "."), `[""]`)
// ...
}
```
Partial fix for …

cli gen: improve flag set defaults from message literals

---

pkg/opni/cliutil/render_metrics.go
pkg/resources/monitoring/cortex/helpers.go
pkg/resources/monitoring/cortex/services.go

Closes : https://github.com/rancher/opni/issues/1750

Relabel cortex services in all-in-one mode

---

pkg/resources/collector/templates.go
pkg/resources/collector/workloads.go
pkg/resources/preprocessor/workloads.go
plugins/logging/pkg/agent/drivers/kubernetes_manager/kubernetes_manager.go

Fixes #1708 
The `filestorage` extension allows us to keep track of the tail offset for every log file watched by the `filelog` receivers. This way, whenever an `opni-collector-agent` pod restarts, they can continue reading the log files from where they stopped.
Previously, whenever a crash or restart happened, agents would read from the start again, sending repeated logs and causing an overflow in the aggregator queues:
```
2023-09-20T14:18:42.911Z	error	exporterhelper/queued_retry.go:216	Dropping data because sending_queue is full. Try increasing queue_size.	{"kind": "exporter", "data_type": "logs", "name": "otlp", "dropped_items": 100}
```
Now, on restarts, this is logged to the `opni-collector-agents`:
```
2023-09-20T15:42:14.081Z	info	extensions/extensions.go:31	Starting …
```

Add storage extension to save filelog receivers' offsets

---

web/pkg/opni/components/MonitoringBackend/index.vue
web/pkg/opni/styles/global/_layout.scss

During the first configuring we do the following:
- Fetch the active config
- Merge the first preset in the list of presets with the active config
- Merge the user config
During subsequent configurations we do the following:
- Fetch the active config
- If the user selects a new preset and press the apply button we'll merge the preset over the active config
- Merge the user config
We also now pass the revision that we get from the active config now

Updating the way we manage the cortex config

---

pkg/alerting/drivers/cortex/cortex.go
plugins/alerting/pkg/alerting/alarms/v1/rules_sync.go
plugins/alerting/pkg/alerting/alarms/v1/setup.go
plugins/alerting/pkg/alerting/alarms/v1/status.go
plugins/alerting/pkg/alerting/alarms/v1/teardown.go
plugins/alerting/pkg/alerting/drivers/alerting_manager/alerting_manager_suite_test.go
plugins/alerting/pkg/alerting/drivers/alerting_manager/cluster_driver.go
plugins/alerting/pkg/alerting/drivers/alerting_manager/driver_test.go
plugins/alerting/pkg/alerting/drivers/alerting_manager/options.go
plugins/alerting/pkg/alerting/system.go
web/pkg/opni/models/alerting/Condition.ts
web/pkg/opni/utils/requests/alerts.ts

- Fixed a change lost in one of the rebases; cluster drivers are only responsible for finding the alerting cluster peers, not initializing clients
- Fixed a bug where an initial install of the alerting cluster would always result in a TLS error
- Fixed a missing edge case where prometheus rules not being present in the metrics backend resulted in an `Ok` status instead of `Pending`
- Fixed a UI bug that made it impossible to delete alert conditions
- Improved the detection of the existence of rule objects in cortex from the alerting plugin

Cert & alerting fixes

---

web/pkg/opni/generated/github.com/rancher/opni/pkg/apis/capability/v1/capability_pb.ts
web/pkg/opni/generated/github.com/rancher/opni/pkg/apis/management/v1/management_svc.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/logging/apis/loggingadmin/loggingadmin_svc.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/metrics/apis/cortexadmin/cortexadmin_svc.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/metrics/apis/cortexops/cortexops_pb.ts
web/pkg/opni/generated/github.com/rancher/opni/plugins/metrics/apis/cortexops/cortexops_svc.ts
web/service-generator/src/index.ts

Previously when a service would return an error we'd fail to deserialize it. This will now get the status error at the very least. It would be nice to get the actual error object but I'm not sure if that's possible yet. It doesn't look like the ErrorInfo object is getting created and I'm not positive if that object is guaranteed for errors.
Old error: 
New error:

Update service generation so we can surface some sort of status error

---

controllers/ai_pretrainedmodel_controller_test.go
pkg/test/alerting/alert_router_gen.go
pkg/util/http_test.go
pkg/util/notifier/notifier.go
pkg/util/notifier/notifier_test.go
plugins/alerting/pkg/alerting/alarms/v1/runner.go
plugins/alerting/pkg/alerting/alarms/v1/streams.go
plugins/alerting/pkg/alerting/system.go
test/integration/agent_mem_test.go
test/plugins/alerting/alerting_test.go
test/plugins/alerting/metrics_test.go
test/plugins/alerting/routing_test.go

Closes : https://github.com/rancher/opni/issues/1758
Disables test in : https://github.com/rancher/opni/issues/1742 
Disables test in : https://github.com/rancher/opni/issues/1764

Flake fixes

---

plugins/logging/pkg/gateway/admin_v2.go

Closes https://github.com/rancher/opni/issues/1816
Context for this fix : After uninstalling and forgetting to delete the opni-quorum PVC, the cluster will fail to initialize (as expected) but the KV won't be populated causing the uninstall request to fail from the management API.

handle uninstall edge case for partial install failures

---

web/pkg/opni/components/MonitoringBackend/index.vue

This will now perform a deep merge which will preserve parts of the config such as storage.

Change the way that we merge presets with existing configs

---

plugins/aiops/pkg/gateway/modeltraining.go

- The AI services expect the KV to be populated before starting, so the original control flow logic was not correct.
- Added a backoff retrier for the initial post to the nats queue to help resolve a race condition that causes a `503` when the AI services are first launched.
Part of https://github.com/rancher/opni/issues/1826

Fix ordering of API tasks for training models

---

dagger/config/config.go

The setup command is writing a file with the `releaser.os` and `releaser.arch` fields as empty lists. This is causing problems in the merge of the default configuration and the configuration generated by the command. During the merge the fields from the files are considered different types causing a failure. As the generate file should be used to overwrite the default values does not make sense to write a file with a invalid field value (empty list). Therefore, this commit change the setup command to remove the mentioned field from the file when they are empty.
Fix #1829

fix: remove empty field in the releaser configuration.

---

plugins/metrics/test/test_drivers.go

Fix panic in testenv metrics cluster driver when reconfiguring after the previous config caused cortex to fail to start

Fix panic in testenv metrics cluster driver

---

packages/opni-agent/opni-agent/charts/Chart.yaml
packages/opni/opni/charts/Chart.yaml
packages/opni/opni/templates/crd-template/Chart.yaml

Now, the Rancher UI asks for the project instead of the name: 
Fixes #1861 
To test, I created an updated "mock" branch called [charts-repo-test-name](https://github.com/rancher/opni/compare/charts-repo...charts-repo-test-name).

Use correct release-name annotation in Charts

---

pkg/logger/color_handler.go
pkg/logger/color_handler_test.go

- logging nil pointer to `encoding.TextMarshaler`
- updates tests to reflect decision to enforce timestamps on all logs
- fixes typo for expected output when dropping an attribute

Fix slog handler edge cases
